### ISSUE TITLE
[Suggestions] Damage, durability loss, and random chance

### ISSUE THREAD

**Issue by DavGam** [fictioncraft-team/CreatureInterlinkage#1]
I'm sorry if these functionalities already exist and I've simply missed them.

I'm hoping to use this to allow players on my server to pluck items such as feathers, bear fur, and similar by right clicking the respective animal with an empty hand.  This works well, but I was hoping to also have this cause some damage to the creature - enough to cause them to run away or fight back.  The upgrade to this was to be doing the same but with shears, which I hoped could reduce the durability of the shears and have only a small chance of causing the damage.  

Sorry if that's complicated - I figured an actual use case would be more helpful than describing functions in the abstract.  I can register each feature as its own feature request if you like.

**Comment by winterSteve25** [comment]
This is not too complicated at all. Thank you for the suggestion, expect an update in 1-2 days :)

**Comment by winterSteve25** [comment]
Hey! This is now implemented. You just need to update FCLib to version 2.2.28, (yes FCLib, not Creature Interlinkage) or above. It should work just fine :)

**Comment by winterSteve25** [comment]
Note: 1.0.0 will not work with version 2.2.29 of FCLib, but that will be fixed shortly.

**Comment by DavGam** [comment]
Brilliant!  Thank you so much ~

**Comment by winterSteve25** [comment]
You got it!:)
